### PR TITLE
update responders config to match default error_status & redirect_status codes for current rails version

### LINKED ISSUE #862: `Create` & `Update` should return `status code != 200` for failed requests
To make `inherited_resources` work with the current version of rails out of the box, it is not allowed to not redirect if status code is 200 on a submitted form.
 
Since on a failure we want to render either `:new` or `:edit`, we are not allowed send status code 200, since this will result in the following error:

```
Error: Form responses must redirect to another location
    at _FormSubmission.requestSucceededWithResponse (application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1298:24)
    at FetchRequest.receive (application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1068:23)
    at FetchRequest.perform (application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1046:27)
formSubmissionErrored @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:2854
requestSucceededWithResponse @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1299
receive @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1068
perform @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1046
await in perform (async)
start @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1258
submitForm @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:2795
formSubmitted @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:3504
FormSubmitObserver.submitBubbled @ application-c20cb2d408231ec629db20f6bfe840b8b84f28b26acee36de46dd6b684b8aa43.js:1457
```

**Workaround:**

```
  def create
    create! do |success, failure|
      failure.html { render(:new, status: :unprocessable_entity) }
    end
  end

  def update
    update! do |success, failure|
      failure.html { render(:edit, status: :unprocessable_entity) }
    end
  end
```

### PR DESCRIPTION
**Pull request by a-nickol**
Update responder class to the current defaults for responder gem. 

Fixes #862

### CODE REVIEW

**Comment by tagliala** [comment]
Any chance to rebase and also test the `see_other` status?

**Comment by a-nickol** [comment]
I am not quite sure if the change is compatible with e.g. active admin etc. 

> Inherited Resources is no longer actively maintained by the original author and has been transferred to the ActiveAdmin organization for maintenance. New feature requests are not encouraged.

Thus I stopped working on the merge request and switched to https://github.com/heartcombo/responders.

Even though Responders has its own bugs, e.g. https://github.com/heartcombo/responders/issues/230.

**Comment by tagliala** [comment]
Any chance to rebase, fix the rubocop offense, and add a spec for the `:see_other` case?

/cc @javierjulio

**Comment by a-nickol** [comment]
I will do the changes if there are any plans that they will be merged.

**Comment by javierjulio** [comment]
The priority is that any change we do continues to work with ActiveAdmin as it did before since it doesn't support Turbo currently. Thank you.

**Comment by tagliala** [comment]
Superseded by #918.

I'm in favor of this change, even if it would need a major version bump to stay conservative.

Thanks @a-nickol, your changes have been preserved in the other PR

**Pull request closed without merging**
