### PR TITLE
Add Rails 7.1 support

### PR DESCRIPTION
**Pull request by tomascco**
I made this PR similar to #707, trying to keep the same structure:
- Updated the "main" Gemfile to Rails 7.1
- Moved the old Gemfile to the `gemfiles` folder
- Updated all Gemfiles

`rake test` passed on my machine with the same output (I think) before this PR

You may also feel free to modify, give feedbacks, etc.

Hope this helps 😄

### CODE REVIEW

**Review by javierjulio — APPROVED** [review]
Thanks! I'll do a separate update to remove the upper bound so we can avoid having to release, assuming no other changes are needed for support. That will close out #711.

**Comment by javierjulio** [comment]
@tomascco there are several deprecation warnings as a result of updating to Rails 7.1. It would help to have a follow up to resolve those if you or someone else is able too. Thank you.

**Comment by tomascco** [comment]
Sure, I'll try my best to tackle those warnings 😃

**Comment by javierjulio** [comment]
Thank you, I appreciate it! If you have trouble feel free to post what you have in a PR and others can jump in.

**Pull request merged**
