### PR TITLE
Remove a bunch of unnecessary stubs in tests

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by javierjulio** [comment]
@deivid-rodriguez awesome thanks! I see Lint CI is failing but didn't Timo turn that off? So I figure it's safe to ignore but I'm now prompted that this branch is out of date with master. Let me know once its ready, thanks!

**Comment by deivid-rodriguez** [comment]
No, LintCI is on. It's just having some trouble when branches use an out of date version of rubocop, apparently. I told @timoschilling about it, he'll probably will have a look at it.

Let me rebase this, and it should be fine.

**Comment by deivid-rodriguez** [comment]
Done!

**Review by javierjulio — APPROVED** [review]
Great! Thanks again too for doing this. ❤️

**Pull request merged**
