### PR TITLE
Drop support for Rails 4.2

### LINKED ISSUE #461: Drop support for Rails 4.2
With Rails 6 on the horizon and with ActiveAdmin already dropping Rails 4.2 support in master, I figured its good we have this in place to review and merge when we are ready for it.

### PR DESCRIPTION
**Pull request by javierjulio**
With Rails 6 on the horizon and with ActiveAdmin already having dropped support for Rails 4.2 in master, I figured its good we have this in place for when we are ready for it.

Closes #461

### CODE REVIEW

**Review by deivid-rodriguez — APPROVED** [review]
Looks awesome to me and I agree with dropping support now. I would only add a note on the README!

**Comment by javierjulio** [comment]
@deivid-rodriguez I wasn't sure where or how to address it on the README but I figured you meant to add it to the CHANGELOG. I added it to the unreleased section. If you still want me to add it to the README though let me know. Happy to do it! Thanks! ❤️

**Comment by deivid-rodriguez** [comment]
No, that was just a mistake, I meant CHANGELOG indeed! :+1:

**Review by deivid-rodriguez — APPROVED** [review]

**Comment by javierjulio** [comment]
@deivid-rodriguez just wanted to say thanks for getting to this so quickly at first! This change will really be a huge help with #459 now. Less Rails changes to account for in tests (e.g. request params) now. Thanks! 👏🏻

**Pull request merged**
