### PR TITLE
Added support for rails 3.1 new mass assignment conventions

### PR DESCRIPTION
**Pull request by somebody32**
I've added new method 'with_role' that can be used to set the role that will be used for 'new' and 'update_attrbutes' methods to satisfy new rails 3.1 mass assignment conventions

### CODE REVIEW

**Comment by josevalim** [comment]
perfect pull request, thanks. merged!

please ping me when Rails 3.1 is out to release a new version?

**Comment by somebody32** [comment]
ping, rails 3.1 is out

**Comment by josevalim** [comment]
Done! thanks for reminding me!

**Comment by njakobsen** [comment]
How are you supposed to use this? I have multiple users with different roles using the same controller to update models. Some attributes are protected and for admins only.

I figured I'd make a before filter that runs the following

```
def set_role
  with_role(current_user.role)
end
```

But it looks like with_role is a class method you call on the controller. How do you apply this in a real use case?

**Comment by Zequez** [comment]
Awesome pull! I was about to do it myself until I saw the changelog! ^^
Thanks!

**Comment by jweir** [comment]
@njakobsen and anyone else trying to dynamically set the role

you might need to overwrite two instance methods:

```
 def role_given?;end # true or false
 def as_role?;end # returns a hash {:as => ROLE}
```

An example with only an :admin role supported

```
def role_given?
  user.is_admin? 
end

def as_role
  user.is_admin? ? {:as => :admin} : {}
end
```

**Pull request merged**
