### PR TITLE
Allow for nesting of singleton belong_to's.

### PR DESCRIPTION
**Pull request by DouweM**
In reference to issue #141.

Note that

``` ruby
class ThingAController < InheritedResources::Base
    belongs_to :thing_b, :singleton => true
end
```

used to mean there was only one `ThingA` (so `resource_path` == `/thing_bs/123/thing_a`), while it now means there is only one `ThingB` (so `resource_path` == `/thing_b/thing_as/123`)

To specify there is only one `ThingA`, you'll need

``` ruby
defaults :singleton => true
```

### CODE REVIEW

**Comment by evserykh** [comment]
:+1:

**Comment by dmitry-a-l** [comment]
:+1:

**Comment by jenkek** [comment]
:+1:

**Comment by seongreen** [comment]
+1

**Comment by joelmoss** [comment]
Any chance you can update your PR please, so it merges cleanly? thx

**Comment by voondo** [comment]
:+1:

**Pull request closed without merging**
