### PR TITLE
Drop support for Rails 5.2

### PR DESCRIPTION
**Pull request by alejandroperea**
I've seen in activeadmin repository that support for Rails 5.2 is being dropped, as it is very close to its EOL (~4-5 months) and only receives security patches.

This PR drops the support for that version and also includes Rails 6.1 and 7.0 in dependabot configuration.

If you think it is too early for this, we can close it and leave it for the future.

### CODE REVIEW

**Review by deivid-rodriguez — APPROVED** [review]
I'm totally up for this!

**Review by rafaelfranca — APPROVED** [review]

**Review by javierjulio — APPROVED** [review]
Thanks!

**Comment by tagliala** [comment]
Hi,

https://github.com/activeadmin/inherited_resources/blob/19bb0b2f37c8b69d3a92ac1166f0601da52f3c23/lib/inherited_resources.rb#L28-L30

Is it possible that this check can be removed as described by the comment? I think that this could have been done after 5.1 removal

Ref: rails/rails#28402

**Comment by deivid-rodriguez** [comment]
Happy to get such a change proposed @tagliala!

**Comment by javierjulio** [comment]
Same here, thanks @tagliala!

**Pull request merged**
