### PR TITLE
 #325 fix: set belongs_to properly for namespaced controller and non_namespaced model

### PR DESCRIPTION
**Pull request by lksv**
this pull request fix issue #325
This issue occurred when controller is in namespace but use model without namespace.

### CODE REVIEW

**Comment by pbhogan** [comment]
:+1:

**Comment by aaronchi** [comment]
:+1:

**Comment by rohitpaulk** [comment]
+1

**Comment by phlegx** [comment]
:+1:

**Comment by aaronchi** [comment]
would be really nice if this could be merged and a new version released. It is holding up other gems like active_admin from using the latest version of IR

**Comment by jasonayre** [comment]
:thumbsup:  +1

@josevalim :)

**Comment by bronislav** [comment]
There are possible problem with `klass.safe_constantize`. In my environment it returns correct result starting from second call. First call always returns wrong result. I will come back with MVE if I will found why it's happens.

**Comment by cknoxrun** [comment]
I've tested this with a whole bunch of controllers in my large app, all seems to work

**Comment by petergoldstein** [comment]
This seems to be relevant to an issue that is locking ActiveAdmin to IR 1.4.x.  You can see the discussion here - https://github.com/activeadmin/activeadmin/pull/3193

**Comment by rafaelfranca** [comment]
Fixed by https://github.com/josevalim/inherited_resources/pull/376

**Pull request closed without merging**
