### PR TITLE
added without_protection feature

### PR DESCRIPTION
**Pull request by aderyabin**
Added without_protection feature already requested in #219.

### CODE REVIEW

**Comment by joelmoss** [comment]
thx

**Comment by urkle** [comment]
Any idea when new release will be made w/ this functionality included?

**Comment by jaredbrown** [comment]
I too would love to see this pushed out as a new gem release.

**Comment by joelmoss** [comment]
This has already been released in v1.4 https://github.com/josevalim/inherited_resources/blob/master/CHANGELOG#L5

**Comment by jaredbrown** [comment]
Thank you, I realized that after I commented.  I didn't see a tag in your repo for 1.4, which is why I was initially confused.

**Pull request merged**
