### PR TITLE
Jruby improvements in CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Little tweaks to jruby in CI.

### CODE REVIEW

**Comment by matheusvetor** [comment]
Sounds great to me

**Review by javierjulio — APPROVED** [review]
Nice to see come through, thanks! 👌🏻

**Comment by javierjulio** [comment]
@deivid-rodriguez sorry, I may have merged PR's out of order. When I was ready to merge this, the branch showed up out of date so I couldn't merge. I figured since I had time to handle this now I'd rebase myself and get this in. Hope you don't mind. There were no conflicts. 👍🏻

**Comment by deivid-rodriguez** [comment]
Only thing is that we also need to update the job incorporated in #482 with the changes made here. I'll do a follow up PR :+1:.

**Pull request merged**
