### PR TITLE
can't get the parent in a polymorphic_belongs_to (rebased)

### PR DESCRIPTION
**Pull request by indrekj**
See https://github.com/josevalim/inherited_resources/pull/158

### CODE REVIEW

**Comment by mdi** [comment]
+1

**Comment by mhfs** [comment]
@josevalim anything I can do to help this get merged? just faced this same issue.

**Comment by mhfs** [comment]
Just confirmed the fix works for my scenario, the branch is 'rebaseble' to master and the tests pass. Hope it helps.

**Comment by josevalim** [comment]
Merged. Thanks @mhfs for actually testing the pull request and giving feedback!

**Comment by mhfs** [comment]
Thank you!

**Pull request merged**
